### ISSUE TITLE
[Bug] Cannot redirect to Playground site with params

### ISSUE THREAD

**Issue by runyasak** [runyasak/vue-playground#4]
I can access playground from this url https://vue-playground.netlify.com/.
However, when I access with params such as https://vue-playground.netlify.com/hello-world. The page not found is appeared.

# Expect Behavior
It could be accessed to `hello-world` normally.

**Comment by YasiOnFire** [comment]
Hi, I've made a PR #5  that fixes this. You can see in the deploy preview that it indeed works. [https://deploy-preview-5--vue-playground.netlify.com/hello-world](https://deploy-preview-5--vue-playground.netlify.com/hello-world)

**Comment by runyasak** [comment]
It works!! 🎉
Thanks for help 😁

@YasiOnFire
